"use client";

import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useState } from "react";
import { AnimatedArrow } from "./AnimatedArrow";
import { StanceAgentLogo } from "./StanceAgentLogo";

const TABS = ["Pipeline", "Features", "Safety"] as const;
type Tab = (typeof TABS)[number];

const PIPELINE = [
  {
    id: "parse_input",
    short: "Parse",
    title: "Parse input",
    detail: "Validates patient ID and message. Assigns a traceable request ID.",
    color: "#6366f1",
  },
  {
    id: "extract_clinical_signals",
    short: "Extract",
    title: "Extract signals",
    detail: "Claude reads free text and returns structured symptoms, onset, and context.",
    color: "#818cf8",
  },
  {
    id: "normalize_symptoms",
    short: "Normalize",
    title: "Normalize symptoms",
    detail: "Maps varied wording to canonical clinical terms for consistent rules.",
    color: "#a78bfa",
  },
  {
    id: "red_flag_detection",
    short: "Red flags",
    title: "Red-flag detection",
    detail: "Deterministic rules scan for emergencies — chest pain, stroke signs, anaphylaxis, etc.",
    color: "#ef4444",
  },
  {
    id: "urgency_classification",
    short: "Urgency",
    title: "Urgency classification",
    detail: "LLM proposes a level; rules can only escalate, never downgrade.",
    color: "#f97316",
  },
  {
    id: "search_decision",
    short: "Decide",
    title: "Search decision",
    detail: "Emergencies skip search for speed. Ambiguous cases trigger evidence retrieval.",
    color: "#eab308",
    branch: true,
  },
  {
    id: "search_medical_sources",
    short: "MCP",
    title: "MCP search",
    detail: "Optional branch: MCP agent queries medical sources. URLs are never fabricated.",
    color: "#22d3ee",
    optional: true,
  },
  {
    id: "merge_evidence",
    short: "Merge",
    title: "Merge evidence",
    detail: "Join point — combines rule output with any retrieved sources.",
    color: "#14b8a6",
  },
  {
    id: "generate_clinical_explanation",
    short: "Explain",
    title: "Clinical explanation",
    detail: "Generates plain-language reasoning and recommended next steps.",
    color: "#6366f1",
  },
  {
    id: "confidence_scoring",
    short: "Score",
    title: "Confidence scoring",
    detail: "Heuristic score from signals + evidence — not LLM self-report.",
    color: "#8b5cf6",
  },
  {
    id: "build_structured_response",
    short: "Respond",
    title: "Build response",
    detail: "Assembles JSON contract + hardcoded disclaimers. Saved to PostgreSQL.",
    color: "#22c55e",
  },
];

const FEATURES = [
  {
    icon: "📋",
    title: "100-case library",
    body: "Virtualized sidebar loads every benchmark case smoothly — search, tap, or navigate.",
  },
  {
    icon: "🔗",
    title: "MCP medical-search agent",
    body: "Streamable HTTP MCP server fetches real URLs for ambiguous presentations.",
  },
  {
    icon: "🐘",
    title: "PostgreSQL history",
    body: "Each triage run persists urgency, confidence, and decision summary per patient.",
  },
  {
    icon: "📱",
    title: "Mobile-ready UI",
    body: "Bottom tabs on phones — Cases, Triage, and Stats — with safe-area support.",
  },
  {
    icon: "🔐",
    title: "Clerk auth (optional)",
    body: "JWT-verified sessions scope history and stats to signed-in users.",
  },
  {
    icon: "📊",
    title: "Live dashboard",
    body: "Urgency breakdown and run counts update after every triage.",
  },
];

const SAFETY = [
  { rule: "LLM proposes, rules dispose", desc: "Red-flag engine can only escalate urgency." },
  { rule: "Hardcoded disclaimers", desc: "Legal text is never generated by the model." },
  { rule: "No fabricated sources", desc: "URLs come verbatim from search tools only." },
  { rule: "Graceful degradation", desc: "Every path returns a safe structured response." },
];

function PipelineGraph({
  activeIndex,
  onSelect,
}: {
  activeIndex: number;
  onSelect: (i: number) => void;
}) {
  return (
    <div className="relative">
      <div className="mb-4 flex items-center justify-between text-xs text-slate-400">
        <span>LangGraph · 11 nodes</span>
        <span className="rounded-full border border-cyan-500/30 bg-cyan-500/10 px-2 py-0.5 text-cyan-300">
          conditional search branch
        </span>
      </div>

      <div className="relative space-y-2">
        {PIPELINE.map((node, i) => {
          const active = i === activeIndex;
          const past = i < activeIndex;
          return (
            <div key={node.id}>
              <motion.button
                type="button"
                onClick={() => onSelect(i)}
                className={`relative flex w-full items-start gap-3 rounded-2xl border px-4 py-3 text-left transition ${
                  active
                    ? "border-cyan-500/50 bg-cyan-500/10 shadow-[0_0_30px_rgba(34,211,238,0.12)]"
                    : past
                      ? "border-white/10 bg-white/[0.03]"
                      : "border-white/5 bg-transparent hover:border-white/15"
                }`}
                animate={active ? { scale: 1.01 } : { scale: 1 }}
              >
                <div
                  className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-[10px] font-bold text-white"
                  style={{ background: `linear-gradient(135deg, ${node.color}, ${node.color}99)` }}
                >
                  {i + 1}
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-semibold text-white">{node.title}</span>
                    {node.optional && (
                      <span className="rounded-full bg-cyan-500/20 px-2 py-0.5 text-[10px] text-cyan-200">
                        if needed
                      </span>
                    )}
                    {node.branch && (
                      <span className="rounded-full bg-amber-500/20 px-2 py-0.5 text-[10px] text-amber-200">
                        branch
                      </span>
                    )}
                  </div>
                  <AnimatePresence mode="wait">
                    {active && (
                      <motion.p
                        className="mt-1 text-xs leading-relaxed text-slate-300"
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                      >
                        {node.detail}
                      </motion.p>
                    )}
                  </AnimatePresence>
                </div>
                {active && (
                  <motion.span
                    className="absolute -left-1 top-1/2 h-8 w-1 -translate-y-1/2 rounded-full bg-cyan-400"
                    layoutId="guide-active-bar"
                  />
                )}
              </motion.button>

              {i < PIPELINE.length - 1 && (
                <div className="flex justify-center py-0.5">
                  <motion.div
                    className="flex flex-col items-center"
                    initial={{ opacity: 0.3 }}
                    animate={{ opacity: past || active ? 1 : 0.35 }}
                  >
                    <div className="h-3 w-px bg-gradient-to-b from-slate-600 to-cyan-500/50" />
                    {node.id === "search_decision" && (
                      <div className="my-1 rounded-lg border border-dashed border-cyan-500/30 px-2 py-1 text-[10px] text-cyan-300/80">
                        ↳ MCP search OR skip → merge
                      </div>
                    )}
                    <motion.div
                      className="h-1.5 w-1.5 rounded-full bg-cyan-400"
                      animate={active ? { y: [0, 6, 0], opacity: [0.4, 1, 0.4] } : {}}
                      transition={{ repeat: Infinity, duration: 1.2 }}
                    />
                  </motion.div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Mini SVG flow diagram — desktop */}
      <div className="mt-6 hidden rounded-2xl border border-white/10 bg-black/20 p-4 sm:block">
        <svg viewBox="0 0 520 120" className="w-full" aria-hidden>
          <defs>
            <linearGradient id="flowGrad" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#6366f1" />
              <stop offset="50%" stopColor="#22d3ee" />
              <stop offset="100%" stopColor="#22c55e" />
            </linearGradient>
          </defs>
          <motion.path
            d="M 20 60 H 500"
            stroke="url(#flowGrad)"
            strokeWidth="2"
            fill="none"
            strokeDasharray="8 6"
            initial={{ pathLength: 0, opacity: 0.3 }}
            animate={{ pathLength: 1, opacity: 0.8 }}
            transition={{ duration: 2, repeat: Infinity, repeatType: "reverse" }}
          />
          {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => (
            <motion.circle
              key={i}
              cx={20 + i * 48}
              cy={60}
              r={i === activeIndex ? 7 : 4}
              fill={PIPELINE[i]?.color ?? "#6366f1"}
              animate={{
                r: i === activeIndex ? [6, 8, 6] : 4,
                opacity: i <= activeIndex ? 1 : 0.35,
              }}
              transition={{ repeat: i === activeIndex ? Infinity : 0, duration: 1.5 }}
            />
          ))}
          <path
            d="M 260 60 Q 280 30 300 45 T 340 60"
            stroke="#22d3ee"
            strokeWidth="1.5"
            fill="none"
            strokeDasharray="4 4"
            opacity="0.6"
          />
          <text x="300" y="38" fill="#67e8f9" fontSize="9" textAnchor="middle">
            MCP
          </text>
        </svg>
        <p className="mt-2 text-center text-[10px] text-slate-500">
          Data flows left → right through each node; search is the only conditional branch.
        </p>
      </div>
    </div>
  );
}

interface VisualGuideModalProps {
  open: boolean;
  onClose: () => void;
}

export function VisualGuideModal({ open, onClose }: VisualGuideModalProps) {
  const [tab, setTab] = useState<Tab>("Pipeline");
  const [activeNode, setActiveNode] = useState(0);
  const [playing, setPlaying] = useState(true);

  useEffect(() => {
    if (!open || !playing || tab !== "Pipeline") return;
    const timer = window.setInterval(() => {
      setActiveNode((i) => (i + 1) % PIPELINE.length);
    }, 2200);
    return () => window.clearInterval(timer);
  }, [open, playing, tab]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 p-0 backdrop-blur-md sm:items-center sm:p-4"
      onClick={onClose}
      role="presentation"
    >
      <motion.div
        className="flex max-h-[92dvh] w-full max-w-2xl flex-col overflow-hidden rounded-t-3xl border border-white/10 bg-[#0a101c] shadow-2xl sm:rounded-3xl"
        initial={{ opacity: 0, y: 40 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 20 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="border-b border-white/10 px-5 py-4 sm:px-7">
          <div className="flex items-start justify-between gap-3">
            <div className="flex items-center gap-3">
              <StanceAgentLogo size={40} />
              <div>
                <h2 className="text-lg font-semibold text-white sm:text-xl">Visual guide</h2>
                <p className="text-xs text-slate-400 sm:text-sm">ViZ Triage agent · visual LangGraph guide</p>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl border border-white/10 px-3 py-1.5 text-sm text-slate-400 hover:text-white"
            >
              Close
            </button>
          </div>

          <div className="mt-4 flex gap-2">
            {TABS.map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => setTab(t)}
                className={`rounded-xl px-4 py-2 text-sm font-medium transition ${
                  tab === t
                    ? "bg-cyan-500/20 text-cyan-100 ring-1 ring-cyan-500/40"
                    : "text-slate-400 hover:bg-white/5"
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5 sm:px-7 sm:py-6">
          <AnimatePresence mode="wait">
            {tab === "Pipeline" && (
              <motion.div
                key="pipeline"
                initial={{ opacity: 0, x: -12 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 12 }}
              >
                <div className="mb-4 flex items-center justify-between">
                  <p className="text-sm text-slate-400">
                    Tap a node or watch the animated walkthrough
                  </p>
                  <button
                    type="button"
                    onClick={() => setPlaying((p) => !p)}
                    className="rounded-lg border border-white/10 px-3 py-1 text-xs text-slate-300 hover:bg-white/5"
                  >
                    {playing ? "Pause tour" : "Play tour"}
                  </button>
                </div>
                <PipelineGraph
                  activeIndex={activeNode}
                  onSelect={(i) => {
                    setActiveNode(i);
                    setPlaying(false);
                  }}
                />
              </motion.div>
            )}

            {tab === "Features" && (
              <motion.div
                key="features"
                className="grid gap-3 sm:grid-cols-2"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                {FEATURES.map((f, i) => (
                  <motion.div
                    key={f.title}
                    className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.06 }}
                  >
                    <div className="mb-2 flex items-center gap-2">
                      <span className="text-lg">{f.icon}</span>
                      <AnimatedArrow delay={i * 0.05} />
                      <span className="text-sm font-semibold text-white">{f.title}</span>
                    </div>
                    <p className="text-xs leading-relaxed text-slate-400">{f.body}</p>
                  </motion.div>
                ))}
              </motion.div>
            )}

            {tab === "Safety" && (
              <motion.div
                key="safety"
                className="space-y-4"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4">
                  <p className="text-sm font-semibold text-red-200">Not emergency care</p>
                  <p className="mt-1 text-xs leading-relaxed text-red-200/80">
                    ViZ Triage agent supports decision-making only. Call emergency services for life-threatening symptoms.
                  </p>
                </div>
                {SAFETY.map((s, i) => (
                  <motion.div
                    key={s.rule}
                    className="flex gap-3 rounded-2xl border border-white/10 p-4"
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.08 }}
                  >
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-emerald-500/20 text-sm text-emerald-300">
                      ✓
                    </div>
                    <div>
                      <p className="text-sm font-medium text-white">{s.rule}</p>
                      <p className="mt-0.5 text-xs text-slate-400">{s.desc}</p>
                    </div>
                  </motion.div>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  );
}
