"""External API contracts — the validation boundary of the system.

Kept separate from ``app/models`` on purpose: internal state can evolve
freely (add fields, refactor) without breaking the public API, and the
public API can never leak internal detail (traces, root causes) by
accident because the response model simply has no fields for them.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import UrgencyLevel


class TriageRequest(BaseModel):
    """POST /triage request body."""

    model_config = ConfigDict(str_strip_whitespace=True)

    patient_id: str = Field(min_length=1, max_length=128, examples=["case_025"])
    message: str = Field(
        min_length=3,
        max_length=8000,
        description="Free-text symptom description from the patient.",
    )


class SourceOut(BaseModel):
    """A cited source. URLs are verbatim from the search tool, never LLM-generated."""

    title: str
    url: str


class TriageResponse(BaseModel):
    """POST /triage response body.

    Matches the interview target output shape:
    patient_message_id, urgency_level, red_flags, triage_decision,
    confidence, reasoning, disclaimers, recommended_action, sources.
    """

    patient_message_id: str
    urgency_level: UrgencyLevel
    red_flags: list[str] = Field(default_factory=list)
    triage_decision: str = Field(
        description="One-sentence triage summary, e.g. 'Immediate emergency care required.'"
    )
    confidence: int = Field(
        ge=0, le=100, description="Deterministic heuristic score — never LLM self-reported."
    )
    reasoning: str = Field(description="Short user-facing explanation (<=100 words). Never chain-of-thought.")
    disclaimers: list[str] = Field(
        description="Hardcoded — injected by the response builder, not generated by the LLM."
    )
    recommended_action: str
    sources: list[str] = Field(
        default_factory=list,
        description="Verified URLs, or empty with a 'No verified external source found.' note in reasoning.",
    )
    request_id: str


class HealthResponse(BaseModel):
    """GET /health response body."""

    status: str
    llm_provider: str
    search_provider: str
    database: str = "unknown"
    database_connected: bool = False
    auth_mode: str = "none"
    mcp_agent: str = ""
    mcp_configured: bool = False
    mcp_connected: bool = False


class ErrorResponse(BaseModel):
    """Uniform error envelope. Never contains stack traces or root causes."""

    error: str
    request_id: str
    detail: str = Field(description="User-safe message only.")
