"""Internal clinical domain models.

Design decision: the LLM is never allowed to "freely interpret" the patient.
The extraction node converts natural language into ``ClinicalSignals`` — a
strict, typed structure. Every downstream node (red flags, urgency, scoring)
operates on this structure, which makes each of them deterministic and
unit-testable without an LLM.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ClinicalSignals(BaseModel):
    """Structured signals extracted from a free-text patient message.

    Fields are Optional because absence of information is itself a signal:
    the confidence scorer penalises missing duration/severity ("missing key
    information -10"), which is impossible if fields are silently defaulted.
    """

    model_config = ConfigDict(frozen=True)

    symptoms: list[str] = Field(
        default_factory=list, description="Normalized symptom terms, e.g. 'chest pain', 'dyspnea'."
    )
    duration: str | None = Field(
        default=None,
        description="How long symptoms have been present, verbatim-normalized, e.g. '20 minutes'.",
    )
    severity: str | None = Field(
        default=None, description="Patient-reported severity, e.g. 'crushing', 'mild'."
    )
    onset: str | None = Field(default=None, description="Sudden vs gradual onset if stated.")
    radiation: str | None = Field(
        default=None, description="Pain radiation pattern if stated, e.g. 'to left arm'."
    )
    age: int | None = Field(
        default=None, ge=0, le=130, description="Age in years, only if explicitly mentioned."
    )
    is_pregnant: bool | None = Field(default=None, description="Pregnancy status; None means not mentioned.")
    medical_history: list[str] = Field(
        default_factory=list, description="Stated history, e.g. 'hypertension', 'epilepsy'."
    )
    medications: list[str] = Field(default_factory=list, description="Current medications if mentioned.")
    allergies: list[str] = Field(default_factory=list, description="Known allergies if mentioned.")
    affects_child: bool = Field(default=False, description="True when the patient describes a child/infant.")
    ambiguity_notes: list[str] = Field(
        default_factory=list,
        description="Vague or contradictory statements flagged by the extractor; feeds confidence scoring.",
    )


class RedFlag(BaseModel):
    """A single detected red flag with provenance.

    ``source`` distinguishes deterministic rule hits from LLM-suggested
    flags — the union is deduplicated, but provenance is preserved for
    auditability and for weighting confidence (rule hits are worth more).
    """

    model_config = ConfigDict(frozen=True)

    name: str = Field(description="Canonical red-flag name, e.g. 'chest pain with radiation'.")
    source: str = Field(description="'rule' (deterministic engine) or 'llm'.")
    matched_text: str | None = Field(
        default=None, description="Patient text fragment that triggered the flag, when available."
    )


class UrgencyAssessment(BaseModel):
    """Output of the urgency classification node.

    Deliberately contains no probability: confidence is computed by a
    separate deterministic scorer. Mixing them invites hallucinated numbers.
    """

    model_config = ConfigDict(frozen=True)

    urgency: str = Field(description="One of: low, moderate, high, emergency.")
    reason: str = Field(description="One-sentence justification, user-safe.")
    supporting_signals: list[str] = Field(
        default_factory=list, description="Which extracted signals drove the classification."
    )


class SearchResult(BaseModel):
    """A single raw result from any SearchTool implementation."""

    model_config = ConfigDict(frozen=True)

    title: str
    summary: str
    url: str
    relevance: float = Field(
        ge=0.0,
        le=1.0,
        description="Provider-reported or heuristic relevance; results below the configured threshold are dropped.",
    )


class GroundedSource(BaseModel):
    """A source that survived relevance filtering and is safe to cite.

    URLs are copied verbatim from the search tool — never generated by the
    LLM — which structurally prevents fabricated citations.
    """

    model_config = ConfigDict(frozen=True)

    title: str
    url: str
    snippet: str
